-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "default"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment.error", { link = "DiagnosticError" })
hi(0, "@comment.note", { link = "DiagnosticInfo" })
hi(0, "@comment.todo", { link = "Todo" })
hi(0, "@comment.warning", { link = "DiagnosticWarn" })
hi(0, "@constant.builtin", { link = "Special" })
hi(0, "@diff.delta", { link = "Changed" })
hi(0, "@diff.minus", { link = "Removed" })
hi(0, "@diff.plus", { link = "Added" })
hi(0, "@function.builtin", { link = "Special" })
hi(0, "@ibl.indent.char.1", { ctermfg = 25, fg = "#2c4c9a" })
hi(0, "@ibl.scope.char.1", { ctermfg = 25, fg = "#2c4c9a", nocombine = true })
hi(0, "@ibl.scope.underline.1", { sp = "#4f5258", underline = true })
hi(0, "@ibl.whitespace.char.1", { ctermfg = 25, fg = "#2c4c9a" })
hi(0, "@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hi(0, "@lsp.type.class", { link = "@type" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.decorator", { link = "@attribute" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { link = "@type" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.macro", { link = "@constant.macro" })
hi(0, "@lsp.type.method", { link = "@function.method" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.namespace", { link = "@module" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.struct", { link = "@type" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.variable", { link = "@variable" })
hi(0, "@markup.heading", { link = "Title" })
hi(0, "@markup.link", { link = "Underlined" })
hi(0, "@module.builtin", { link = "Special" })
hi(0, "@number.float", { link = "Float" })
hi(0, "@punctuation.special", { link = "Special" })
hi(0, "@string.escape", { link = "@string.special" })
hi(0, "@string.regexp", { link = "@string.special" })
hi(0, "@string.special", { link = "SpecialChar" })
hi(0, "@string.special.url", { link = "Underlined" })
hi(0, "@tag.builtin", { link = "Special" })
hi(0, "@type.builtin", { link = "Special" })
hi(0, "@variable", { ctermfg = 254, fg = "#dce1f8" })
hi(0, "@variable.builtin", { link = "Special" })
hi(0, "@variable.parameter.builtin", { link = "Special" })
hi(0, "Added", { ctermfg = 121, fg = "#8bffa8" })
hi(0, "Changed", { ctermfg = 87, fg = "#4effff" })
hi(0, "CmpItemAbbrDeprecatedDefault", { ctermfg = 110, fg = "#869ecf" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindDefault", { ctermfg = 87, fg = "#4effff" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "ColorColumn", { bg = "#43464c", ctermbg = 238 })
hi(0, "Comment", { ctermfg = 110, fg = "#869ecf" })
hi(0, "Conceal", { ctermfg = 25, fg = "#2c4c9a" })
hi(0, "Constant", { ctermfg = 254, fg = "#dce1f8" })
hi(0, "CurSearch", { bg = "#eed286", ctermbg = 186, ctermfg = 232, fg = "#05061b" })
hi(0, "Cursor", { bg = "#d2d4dc", ctermbg = 188, ctermfg = 233, fg = "#0a1333" })
hi(0, "CursorColumn", { bg = "#202227", ctermbg = 235 })
hi(0, "CursorLine", { bg = "#202227", ctermbg = 235 })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, ctermfg = 155, fg = "#a5ff5e" })
hi(0, "DapUIBreakpointsDisabledLine", { ctermfg = 238, fg = "#424242" })
hi(0, "DapUIBreakpointsInfo", { ctermfg = 155, fg = "#a5ff5e" })
hi(0, "DapUIBreakpointsPath", { ctermfg = 51, fg = "#00f1f5" })
hi(0, "DapUIDecoration", { ctermfg = 51, fg = "#00f1f5" })
hi(0, "DapUIFloatBorder", { ctermfg = 51, fg = "#00f1f5" })
hi(0, "DapUILineNumber", { ctermfg = 51, fg = "#00f1f5" })
hi(0, "DapUIModifiedValue", { bold = true, ctermfg = 51, fg = "#00f1f5" })
hi(0, "DapUINormalNC", { bg = "#07080d", ctermbg = 232, ctermfg = 254, fg = "#dce1f8" })
hi(0, "DapUIPlayPause", { ctermfg = 155, fg = "#a5ff5e" })
hi(0, "DapUIPlayPauseNC", { bg = "#000000", ctermbg = 16, ctermfg = 155, fg = "#a5ff5e" })
hi(0, "DapUIRestart", { ctermfg = 155, fg = "#a5ff5e" })
hi(0, "DapUIRestartNC", { bg = "#000000", ctermbg = 16, ctermfg = 155, fg = "#a5ff5e" })
hi(0, "DapUIScope", { ctermfg = 51, fg = "#00f1f5" })
hi(0, "DapUISource", { ctermfg = 177, fg = "#d680ff" })
hi(0, "DapUIStepBack", { ctermfg = 51, fg = "#00f1f5" })
hi(0, "DapUIStepBackNC", { bg = "#000000", ctermbg = 16, ctermfg = 51, fg = "#00f1f5" })
hi(0, "DapUIStepInto", { ctermfg = 51, fg = "#00f1f5" })
hi(0, "DapUIStepIntoNC", { bg = "#000000", ctermbg = 16, ctermfg = 51, fg = "#00f1f5" })
hi(0, "DapUIStepOut", { ctermfg = 51, fg = "#00f1f5" })
hi(0, "DapUIStepOutNC", { bg = "#000000", ctermbg = 16, ctermfg = 51, fg = "#00f1f5" })
hi(0, "DapUIStepOver", { ctermfg = 51, fg = "#00f1f5" })
hi(0, "DapUIStepOverNC", { bg = "#000000", ctermbg = 16, ctermfg = 51, fg = "#00f1f5" })
hi(0, "DapUIStop", { ctermfg = 197, fg = "#f70067" })
hi(0, "DapUIStopNC", { bg = "#000000", ctermbg = 16, ctermfg = 197, fg = "#f70067" })
hi(0, "DapUIStoppedThread", { ctermfg = 51, fg = "#00f1f5" })
hi(0, "DapUIThread", { ctermfg = 155, fg = "#a5ff5e" })
hi(0, "DapUIType", { ctermfg = 177, fg = "#d680ff" })
hi(0, "DapUIUnavailable", { ctermfg = 238, fg = "#424242" })
hi(0, "DapUIUnavailableNC", { bg = "#000000", ctermbg = 16, ctermfg = 238, fg = "#424242" })
hi(0, "DapUIWatchesEmpty", { ctermfg = 197, fg = "#f70067" })
hi(0, "DapUIWatchesError", { ctermfg = 197, fg = "#f70067" })
hi(0, "DapUIWatchesValue", { ctermfg = 155, fg = "#a5ff5e" })
hi(0, "DapUIWinSelect", { bold = true, ctermfg = 51, fg = "#00f1f5" })
hi(0, "Delimiter", { ctermfg = 254, fg = "#dce1f8" })
hi(0, "DiagnosticError", { ctermfg = 217, fg = "#ffbab2" })
hi(0, "DiagnosticHint", { ctermfg = 153, fg = "#a3dbff" })
hi(0, "DiagnosticInfo", { ctermfg = 87, fg = "#4effff" })
hi(0, "DiagnosticOk", { ctermfg = 121, fg = "#8bffa8" })
hi(0, "DiagnosticWarn", { ctermfg = 222, fg = "#ffdf85" })
hi(0, "DiffAdd", { bg = "#00471b", ctermbg = 237, ctermfg = 255, fg = "#ebf1ff" })
hi(0, "DiffChange", { bg = "#43464c", ctermbg = 238, ctermfg = 255, fg = "#ebf1ff" })
hi(0, "DiffDelete", { bold = true, ctermfg = 217, fg = "#ffbab2" })
hi(0, "DiffText", { bg = "#006565", ctermbg = 23, ctermfg = 255, fg = "#ebf1ff" })
hi(0, "Directory", { ctermfg = 87, fg = "#4effff" })
hi(0, "EndOfBuffer", { blend = 0, link = "NonText" })
hi(0, "Error", { bg = "#440005", ctermbg = 52, ctermfg = 255, fg = "#ebf1ff" })
hi(0, "ErrorMsg", { ctermfg = 217, fg = "#ffbab2" })
hi(0, "FloatShadow", { bg = "#43464c", blend = 80, ctermbg = 238 })
hi(0, "FloatShadowThrough", { bg = "#43464c", blend = 100, ctermbg = 238 })
hi(0, "FoldColumn", { blend = 0, link = "SignColumn" })
hi(0, "Folded", { bg = "#202227", ctermbg = 235, ctermfg = 110, fg = "#869ecf" })
hi(0, "Function", { ctermfg = 87, fg = "#4effff" })
hi(0, "GitSignsStagedAdd", { ctermfg = 29, fg = "#34844c" })
hi(0, "GitSignsStagedAddLn", { bg = "#00471b", ctermbg = 237, ctermfg = 97, fg = "#6773b5" })
hi(0, "GitSignsStagedAddNr", { ctermfg = 29, fg = "#34844c" })
hi(0, "GitSignsStagedChange", { ctermfg = 30, fg = "#008281" })
hi(0, "GitSignsStagedChangeLn", { bg = "#43464c", ctermbg = 238, ctermfg = 97, fg = "#6773b5" })
hi(0, "GitSignsStagedChangeNr", { ctermfg = 30, fg = "#008281" })
hi(0, "GitSignsStagedChangedelete", { ctermfg = 30, fg = "#008281" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#43464c", ctermbg = 238, ctermfg = 97, fg = "#6773b5" })
hi(0, "GitSignsStagedChangedeleteNr", { ctermfg = 30, fg = "#008281" })
hi(0, "GitSignsStagedDelete", { ctermfg = 131, fg = "#a5473f" })
hi(0, "GitSignsStagedDeleteNr", { ctermfg = 131, fg = "#a5473f" })
hi(0, "GitSignsStagedTopdelete", { ctermfg = 131, fg = "#a5473f" })
hi(0, "GitSignsStagedTopdeleteNr", { ctermfg = 131, fg = "#a5473f" })
hi(0, "IblIndent", { link = "NonText" })
hi(0, "IblScope", { ctermfg = 25, fg = "#2c4c9a" })
hi(0, "IblWhitespace", { link = "NonText" })
hi(0, "Identifier", { ctermfg = 153, fg = "#a3dbff" })
hi(0, "LineNr", { blend = 0, ctermfg = 25, fg = "#2c4c9a" })
hi(0, "LineNrAbove", { blend = 0, link = "LineNr" })
hi(0, "LineNrBelow", { blend = 0, link = "LineNr" })
hi(0, "LspCodeLens", { link = "WarningMsg" })
hi(0, "LspCodeLensSeparator", { link = "Boolean" })
hi(0, "LspDiagnosticsSignHint", { blend = 0 })
hi(0, "LspReferenceRead", { link = "IncSearch" })
hi(0, "LspReferenceWrite", { link = "Search" })
hi(0, "MatchParen", { bg = "#43464c", bold = true, ctermbg = 238 })
hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
hi(0, "MiniCompletionActiveParameter", { underline = true })
hi(0, "ModeMsg", { ctermfg = 121, fg = "#8bffa8" })
hi(0, "MoreMsg", { ctermfg = 87, fg = "#4effff" })
hi(0, "MsgArea", { blend = 0 })
hi(0, "MsgSeparator", { blend = 0, link = "StatusLine" })
hi(0, "NGHiReference_1_1", { bg = "#4270ef", ctermbg = 63, ctermfg = 154, fg = "#adfe00" })
hi(0, "NGHiReference_1_2", { bg = "#4270ef", ctermbg = 63, ctermfg = 148, fg = "#aede00" })
hi(0, "NGHiReference_1_3", { bg = "#4270ef", ctermbg = 63, ctermfg = 142, fg = "#aebe00" })
hi(0, "NGHiReference_2_1", { bg = "#f0d0f0", ctermbg = 225, ctermfg = 200, fg = "#ff00e0" })
hi(0, "NGHiReference_2_2", { bg = "#f0d0f0", ctermbg = 225, ctermfg = 164, fg = "#df01e0" })
hi(0, "NGHiReference_2_3", { bg = "#f0d0f0", ctermbg = 225, ctermfg = 128, fg = "#af02e0" })
hi(0, "NGHiReference_3_1", { bg = "#e2e228", ctermbg = 184, ctermfg = 21, fg = "#1000ef" })
hi(0, "NGHiReference_3_2", { bg = "#e2e228", ctermbg = 184, ctermfg = 20, fg = "#2000df" })
hi(0, "NGHiReference_3_3", { bg = "#e2e228", ctermbg = 184, ctermfg = 20, fg = "#2000d0" })
hi(0, "NGHiReference_4_1", { bg = "#412027", ctermbg = 236, ctermfg = 210, fg = "#f9968e" })
hi(0, "NGHiReference_4_2", { bg = "#412027", ctermbg = 236, ctermfg = 210, fg = "#ec978b" })
hi(0, "NGHiReference_4_3", { bg = "#412027", ctermbg = 236, ctermfg = 210, fg = "#dd9983" })
hi(0, "NGHiReference_5_1", { bg = "#0034e7", ctermbg = 21, ctermfg = 214, fg = "#ffa726" })
hi(0, "NGHiReference_5_2", { bg = "#0034e7", ctermbg = 21, ctermfg = 178, fg = "#f29e00" })
hi(0, "NGHiReference_5_3", { bg = "#0034e7", ctermbg = 21, ctermfg = 178, fg = "#e2a600" })
hi(0, "NGHiReference_6_1", { bg = "#df4082", ctermbg = 168, ctermfg = 148, fg = "#aedd00" })
hi(0, "NGHiReference_6_2", { bg = "#df4082", ctermbg = 168, ctermfg = 41, fg = "#00dc4a" })
hi(0, "NGHiReference_6_3", { bg = "#df4082", ctermbg = 168, ctermfg = 41, fg = "#00d147" })
hi(0, "NonText", { ctermfg = 25, fg = "#2c4c9a" })
hi(0, "Normal", { blend = 0, ctermfg = 254, fg = "#dce1f8" })
hi(0, "NormalFloat", { bg = "#000000", ctermbg = 16 })
hi(0, "NormalNC", { blend = 0 })
hi(0, "NvimInternalError", { bg = "#e80000", ctermbg = 160, ctermfg = 196, fg = "#ff0000" })
hi(0, "Operator", { ctermfg = 254, fg = "#dce1f8" })
hi(0, "Pmenu", { bg = "#202227", ctermbg = 235 })
hi(0, "PmenuSel", { bg = "#d2d4dc", blend = 0, ctermbg = 188, ctermfg = 236, fg = "#1b2a5b" })
hi(0, "PmenuThumb", { bg = "#43464c", ctermbg = 238 })
hi(0, "PreProc", { ctermfg = 254, fg = "#dce1f8" })
hi(0, "Question", { ctermfg = 87, fg = "#4effff" })
hi(0, "QuickFixLine", { ctermfg = 87, fg = "#4effff" })
hi(0, "RedrawDebugClear", { bg = "#5c4700", ctermbg = 239, ctermfg = 0 })
hi(0, "RedrawDebugComposed", { bg = "#00471b", ctermbg = 237, ctermfg = 0 })
hi(0, "RedrawDebugRecompose", { bg = "#440005", ctermbg = 52, ctermfg = 0 })
hi(0, "Removed", { ctermfg = 217, fg = "#ffbab2" })
hi(0, "Search", { bg = "#5c4700", ctermbg = 239, ctermfg = 255, fg = "#ebf1ff" })
hi(0, "SignColumn", { blend = 0, ctermfg = 25, fg = "#2c4c9a" })
hi(0, "Special", { ctermfg = 87, fg = "#4effff" })
hi(0, "SpecialKey", { ctermfg = 25, fg = "#2c4c9a" })
hi(0, "Statement", { bold = true, ctermfg = 254, fg = "#dce1f8" })
hi(0, "StatusLine", { bg = "#b6b8bf", ctermbg = 250, ctermfg = 236, fg = "#1b2a5b" })
hi(0, "StatusLineNC", { bg = "#202227", ctermbg = 235, ctermfg = 251, fg = "#bcc5e7" })
hi(0, "String", { ctermfg = 121, fg = "#8bffa8" })
hi(0, "Title", { bold = true, ctermfg = 254, fg = "#dce1f8" })
hi(0, "Todo", { bold = true, ctermfg = 254, fg = "#dce1f8" })
hi(0, "TodoBgFIX", { bg = "#f0b2ab", bold = true, ctermbg = 217, ctermfg = 233, fg = "#0a1333" })
hi(0, "TodoBgHACK", { bg = "#eed286", bold = true, ctermbg = 186, ctermfg = 233, fg = "#0a1333" })
hi(0, "TodoBgNOTE", { bg = "#98cdf1", bold = true, ctermbg = 117, ctermfg = 233, fg = "#0a1333" })
hi(0, "TodoBgPERF", { bg = "#98cdf1", bold = true, ctermbg = 117, ctermfg = 233, fg = "#0a1333" })
hi(0, "TodoBgTEST", { bg = "#98cdf1", bold = true, ctermbg = 117, ctermfg = 233, fg = "#0a1333" })
hi(0, "TodoBgTODO", { bg = "#7deae9", bold = true, ctermbg = 116, ctermfg = 233, fg = "#0a1333" })
hi(0, "TodoBgWARN", { bg = "#eed286", bold = true, ctermbg = 186, ctermfg = 233, fg = "#0a1333" })
hi(0, "TodoFgFIX", { ctermfg = 217, fg = "#ffbab2" })
hi(0, "TodoFgHACK", { ctermfg = 222, fg = "#ffdf85" })
hi(0, "TodoFgNOTE", { ctermfg = 153, fg = "#a3dbff" })
hi(0, "TodoFgPERF", { ctermfg = 153, fg = "#a3dbff" })
hi(0, "TodoFgTEST", { ctermfg = 153, fg = "#a3dbff" })
hi(0, "TodoFgTODO", { ctermfg = 87, fg = "#4effff" })
hi(0, "TodoFgWARN", { ctermfg = 222, fg = "#ffdf85" })
hi(0, "TodoSignFIX", { blend = 0, ctermfg = 217, fg = "#ffbab2" })
hi(0, "TodoSignHACK", { blend = 0, ctermfg = 222, fg = "#ffdf85" })
hi(0, "TodoSignNOTE", { blend = 0, ctermfg = 153, fg = "#a3dbff" })
hi(0, "TodoSignPERF", { blend = 0, ctermfg = 153, fg = "#a3dbff" })
hi(0, "TodoSignTEST", { blend = 0, ctermfg = 153, fg = "#a3dbff" })
hi(0, "TodoSignTODO", { blend = 0, ctermfg = 87, fg = "#4effff" })
hi(0, "TodoSignWARN", { blend = 0, ctermfg = 222, fg = "#ffdf85" })
hi(0, "Type", { ctermfg = 254, fg = "#dce1f8" })
hi(0, "VertSplit", { blend = 0, link = "WinSeparator" })
hi(0, "Visual", { bg = "#43464c", ctermbg = 238, ctermfg = 0 })
hi(0, "WarningMsg", { ctermfg = 222, fg = "#ffdf85" })
hi(0, "WinBar", { bg = "#000000", bold = true, ctermbg = 16, ctermfg = 110, fg = "#869ecf" })
hi(0, "WinBarNC", { bg = "#000000", ctermbg = 16, ctermfg = 110, fg = "#869ecf" })
hi(0, "WinSeparator", { blend = 0, link = "Normal" })
hi(0, "goCoverageCovered", { blend = 0, link = "String" })
hi(0, "goCoveragePartial", { blend = 0, link = "WarningMsg" })
hi(0, "goCoverageUncovered", { blend = 0, link = "Error" })
hi(0, "lCursor", { bg = "#d2d4dc", ctermbg = 188, ctermfg = 233, fg = "#0a1333" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#07080d"
g.terminal_color_1 = "#ffbab2"
g.terminal_color_2 = "#8bffa8"
g.terminal_color_3 = "#ffdf85"
g.terminal_color_4 = "#dce1f8"
g.terminal_color_5 = "#f0d0f0"
g.terminal_color_6 = "#4effff"
g.terminal_color_7 = "#dce1f8"
g.terminal_color_8 = "#07080d"
g.terminal_color_9 = "#ffbab2"
g.terminal_color_10 = "#8bffa8"
g.terminal_color_11 = "#ffdf85"
g.terminal_color_12 = "#dce1f8"
g.terminal_color_13 = "#f0d0f0"
g.terminal_color_14 = "#4effff"
g.terminal_color_15 = "#dce1f8"
